services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


  springboot-app:
    build: .
    container_name: spring-boot
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379